version: '3.8'

services:
  mongo1:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    networks:
      - mongoCluster
    volumes:
      - ${MONGO1_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo2:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    networks:
      - mongoCluster
    volumes:
      - ${MONGO2_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongo3:
    image: mongo:5
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    networks:
      - mongoCluster
    volumes:
      - ${MONGO3_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  flask-predict-app:
    image: ahmadkais/flask-predict-app:0.0.7
    ports:
      - "8081:8081"
    networks:
      - mongoCluster
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - $HOME/.aws:/root/.aws

  polybot:
    image: ahmadkais/polybot:0.0.3
    ports:
      - "8443:8443"
    networks:
      - mongoCluster
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_APP_URL=${TELEGRAM_APP_URL}
      - S3_BUCKET=${S3_BUCKET}
      - YOLO_SERVICE_URL=${YOLO_SERVICE_URL}
    volumes:
      - /home/ubuntu/YOURPUBLIC.pem:/app/YOURPUBLIC.pem
      - /home/ubuntu/YOURPRIVATE.key:/app/YOURPRIVATE.key
      - $HOME/.aws:/root/.aws

networks:
  mongoCluster:
    driver: bridge
